sudo: required

services: docker

language: php

before_install:
  - docker build -t php-mime-mail-parser/php-mime-mail-parser .
  - docker run php-mime-mail-parser/php-mime-mail-parser /bin/sh -c "php -v"
