sudo: required

services: docker

env:
  - PMMP="1"
  - PMMP="2"
  - PMMP="3"

before_install:
  - if [[ "$PMMP" = "1" ]]; then docker build -f Dockerfile-php70 -t php-mime-mail-parser/php-mime-mail-parser . ; fi
  - if [[ "$PMMP" = "2" ]]; then docker build -f Dockerfile-php70-mbstring -t php-mime-mail-parser/php-mime-mail-parser . ; fi
  - if [[ "$PMMP" = "3" ]]; then docker build -f Dockerfile-php70-compiled -t php-mime-mail-parser/php-mime-mail-parser . ; fi
  - docker run php-mime-mail-parser/php-mime-mail-parser /bin/sh -c "php -v"
  - docker run php-mime-mail-parser/php-mime-mail-parser /bin/sh -c "php -m"

before_script:
  - docker run php-mime-mail-parser/php-mime-mail-parser /bin/sh -c "composer self-update"
  - docker run php-mime-mail-parser/php-mime-mail-parser /bin/sh -c "composer update $COMPOSER_OPTS"

script:
  - docker run php-mime-mail-parser/php-mime-mail-parser /bin/sh -c "mkdir -p build/logs"
  - docker run php-mime-mail-parser/php-mime-mail-parser /bin/sh -c "./vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml"
  - docker run php-mime-mail-parser/php-mime-mail-parser /bin/sh -c  "./vendor/bin/phpcs src --standard=psr2"
  - docker run php-mime-mail-parser/php-mime-mail-parser /bin/sh -c "./vendor/bin/phpcs tests --standard=psr2"

after_script:
  - docker run php-mime-mail-parser/php-mime-mail-parser /bin/sh -c "./vendor/bin/coveralls -v"
