language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - nightly

env:
    - COMPOSER_OPTS="" FORCE_MBSTRING=true
    - COMPOSER_OPTS="--prefer-lowest" FORCE_MBSTRING=false

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

sudo: false
before_install: 
    - phpdismod mbstring
    - if [ $FORCE_MBSTRING = true ]; then sudo apt-get remove -y php-mbstring foo; else sudo apt-get install -y php-mbstring; fi
    - pecl install mailparse

before_script:
    - composer self-update
    - composer update $COMPOSER_OPTS

script:
    - mkdir -p build/logs
    - ./vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
    - ./vendor/bin/phpcs src --standard=psr2
    - ./vendor/bin/phpcs tests --standard=psr2

after_script:
    - ./vendor/bin/coveralls -v
