name: CI

on: [push]

jobs:

  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.1, 7.2, 7.3]
        composer: ["", "--prefer-lowest"]
    
    steps:
    - uses: actions/checkout@v1
    - name: Change PHP version
      run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}
    - name: Install mailparse
      run: sudo apt install php-mailparse
    - name: Composer install
      run: composer update ${{ matrix.composer }} --no-progress
    - name: PHP Version
      run: php -v
    - name: PhpUnit
      run: |
        mkdir -p build/logs
        ./vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml -c phpunit.xml.dist --whitelist src
    - name: PHPCS
      run: |
        ./vendor/bin/phpcs src --standard=psr2
        ./vendor/bin/phpcs tests --standard=psr2
    - name: Git info
      run: git remote set-url origin https://eXorus:${{ secrets.GITHUB_TOKEN }}@github.com/php-mime-mail-parser/php-mime-mail-parser
    - name: Auto Commit
      run: |
        git status
        git remote get-url --all origin
        git config --global user.email "you@example.com"
        git config --global user.name "PHP CS Fixer"
        git add -A
        git commit -m "test" || echo "No changes found. Nothing to commit."
        git push -u origin HEAD
    - name: Coveralls
      env:
        COVERALLS_REPO_TOKEN: BS4E6dtQa8fUMHQiOTFbQICA6ydxSqkRt
      run: ./vendor/bin/php-coveralls -v
     
